// Code generated by logcopter-gen; DO NOT EDIT.

package steps

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.uhoh.pkg.wizard.steps")
